### ISSUE TITLE
Binaries don't seem to work in MacOS

### ISSUE THREAD

**Issue by gpvillamil** [DanielArnett/360-VJ#5] opened 2019-12-02 22:38 UTC
I've pointed my new install of Resolume 7 to the same folder of FFGL plugins that I used for Resolume 6, and the plugins don't appear.

This is MacOS Mojave 10.14.6 and Resolume 7.05

Perhaps needs to be updated to latest version of FFGL?

**Comment by DanielArnett** [comment] 2019-12-02 22:42
@jorisdejong what did you do to update the Windows binaries other than change to VS2019? Is there a new version of FFGL we need to update to?

**Comment by jorisdejong** [comment] 2019-12-02 23:14
I did not make any changes aside from updating the project version.

There is a new version of the SDK, but the core functionality, that your
plugins are using, hasn’t changed.

**Comment by DanielArnett** [comment] 2019-12-03 01:33
TL;DR someone just needs to pull my latest commit and rebuild the OSX binaries.

It looks like [Resolume updated to FFGL2.1](https://github.com/resolume/ffgl) and any version of Resolume 7.0.3 or greater will need FFGL2.1. I updated the FFGL submodule, so now we just need to 
 pull my latest commmit and build it. Unfortunately I can't at the moment (need to ssh into a remote machine that's turned off), so if anyone else gets to it before I can then send me a message.

**Comment by jamesBenja** [comment] 2020-08-29 20:54
Hey @DanielArnett !
I'm having the same issue listed above with resolume 7 and the plugins not appearing in the effects folder.
Has this issue been sorted out? Is there an alternate download I can use that will work?
Thanks!

**Comment by giittyy** [comment] 2020-10-14 00:30
Same issue. How would I build it?

**Comment by DanielArnett** [comment] 2020-10-14 02:26
Unfortunately I don't have access to a Mac anymore, which is why these don't work. 

The first step would be to get the AddSubtract example building from Resolume
https://github.com/resolume/ffgl

Then slowly move my code into that project, first by changing the inputs and then eventually by copying the shader itself.

**Comment by onemoabyte** [comment] 2021-03-25 02:23
are you able to install the macOS on your PC? I'd love to get these working on Mac again.

**Comment by xinaesthete** [comment] 2023-01-31 11:07
I'm thinking of having a go at getting this working. Actually I'm making a start now, but I should really stop distracting myself and get back to more urgent things soon...

If I manage to make some progress, I'll try to remember to post here.

**Comment by xinaesthete** [comment] 2023-01-31 12:56
Small update: had some initial trouble getting example ffgl plugin to work, but have now managed https://github.com/resolume/ffgl/issues/89

**Comment by xinaesthete** [comment] 2023-01-31 13:52
@onemoabyte 
More significant update: I have built a working (on my machine™️) version of `EquiToFisheye`. 🎉

I might arrange things a bit differently if I continue to work on this, but for now I've added a bundle of that to an ffgl fork: https://github.com/xinaesthete/ffgl-360/tree/master/dist

I don't work all that much with C++, did need a couple of minor alterations to get `EquiToFisheye` working - I changed `sprintf_s` to `sprintf`, `CFreeFrameGLPlugin` to `CFFGLPlugin` (as per ffgl 2.2). I think that was about it. I haven't really looked at the resulting visuals much - it did some plausibly wacky distortion on the non-equirectangular clip I tested it on, so I assume it's doing the right thing.

**Comment by xinaesthete** [comment] 2023-01-31 14:48
I built the rest of the plugins https://github.com/xinaesthete/ffgl-360/releases/tag/0.2

Not tested at all yet. Entirely possible I made some mistake somewhere down the line and ended up with two copies of one with a different name or something, but hopefully should all be ok. LMK.

**Comment by DanielArnett** [comment] 2023-01-31 18:01
Fantastic, thanks! I'll try them out sometime and get back to you.

**Comment by xinaesthete** [comment] 2023-01-31 18:32
Great, nice to have a response.

I was thinking that there was an issue with the `EquiRotation` and seams along the edge of the image, but it seems that the problem was me not having the right 'maximise video' setting.

While I'm here, it seems there's no "360 To Flat" projection (possible via `360 To Fisheye` -> `Fisheye To Flat`, so not a particular problem), is that right?

**Comment by DanielArnett** [comment] 2023-01-31 18:55
I can get that working if you want. I wrote the math to go between all of the common projections (equirectangular, rectilinear, fisheye, cubemap, EquiAngularCubemap) to any other projection. If we had dropdown boxes we could just put all of this functionality into one plugin. [This page of mine shows it working](https://danielarnett.github.io/360GL/).

**Comment by xinaesthete** [comment] 2023-01-31 19:09
> I can get that working if you want. I wrote the math to go between all of the common projections (equirectangular, rectilinear, fisheye, cubemap, EquiAngularCubemap) to any other projection. If we had dropdown boxes we could just put all of this functionality into one plugin. [This page of mine shows it working](https://danielarnett.github.io/360GL/).

Interesting, I'll be having a bit of a read through the source of that as well. It seems like it'd make sense to do it that way, not essential. It's fun having the separate stages for playing with stuff like `PolarKaleido`, but it wouldn't take away the ability to do any of that doing what you describe.

**Comment by xinaesthete** [comment] 2023-01-31 19:15
I should probably try to merge my changes back into your repo and make a PR?

**Comment by xinaesthete** [comment] 2023-01-31 19:29
Actually, it seem like depending on the composition resolution, there can be issues with loss of resolution as it goes through reprojection, and there'll be some overhead in having multiple instances (especially at higher resolutions) so there could be good reasons for being able to do as much of the maths in one pass as possible.

**Comment by DanielArnett** [comment] 2023-01-31 19:48
Absolutely, and sometimes it's just easier to do multiple steps, especially
when dealing with euler angles for rotations. Yeah I've just been putting
this off because I haven't had an OSX dev environment in a while. I'll try
to find some time to update this on windows.

Also yes a PR would be great.

**Comment by xinaesthete** [comment] 2023-02-01 10:53
Slight problem when I try to clone with submodules

```
Submodule 'ffgl' (https://github.com/resolume/ffgl.git) registered for path 'ffgl/ffgl'
Submodule 'ffgl/ffgl1.5' (https://github.com/resolume/ffgl.git) registered for path 'ffgl/ffgl1.5'
Cloning into '/Users/petertodd/code/360-VJ/ffgl/ffgl'...
fatal: /Users/petertodd/code/360-VJ/.git/modules/ffgl already exists
```

To get the build working before, I ignored that and did as you suggested above: worked against a fork of ffgl, copied your code into there and did the various bits of xcode configuration and minor code edits needed.

I imagine the way it should be is something like a `build/mac` folder with `.xcodeproj` &co, with relative paths to `../../../ffgl` equivalent to the VS config.

Once that is working, if we want to still be able to build against older versions of ffgl, I don't know if the change `CFreeFrameGLPlugin` -> `CFFGLPlugin` will cause any issues? For ref, [this commit](https://github.com/resolume/ffgl/commit/5c6e0064faf20821de882b13312cc8b0767d4334) in `resolume/ffgl`. I assume it'd mean that you'd need to make that change on Windows as well.

In fact, what I might do next is try cloning the project on a Windows machine. If I don't have trouble with submodules, I can verify that the build breaks because of `CFreeFrameGLPlugin` not existing, and make a first PR just with that change to `CFFGLPlugin`.

I suppose if necessary we could have a `#define` for that depending on the ffgl version to build against, but I'm not strongly motivated to configure that and wouldn't have a way of testing it I don't think. I suppose anyone using older versions of Resolume or whatever would still be able to make do with the existing releases anyway.

**Comment by philipkrueger** [comment] 2023-02-08 10:28
Thank you so much!! Equi rotation isn't seamless yet but all in all great work!!

**Comment by DanielArnett** [comment] 2023-02-08 16:06
What do you mean not seamless? I've seen edges in how it wraps and removed them before. Can you post a screenshot?

**Comment by DanielArnett** [comment] 2023-02-08 20:20
Nice I've seen that one in other projects, it's an easy fix in the shader.
I'm still tracking this issue, I just need to sit down this weekend and
look at it and the PR.

**Comment by philipkrueger** [comment] 2023-02-09 12:59
I found other minor bugs: 
Flat to 360: It seems that pixel colors from the border of the input image tint the surrounding of the output. I could solve it by adding a tiny vignette on the input but I think it should be just transparent in general.
<img width="451" alt="Bildschirm­foto 2023-02-08 um 20 00 24" src="https://user-images.githubusercontent.com/15050074/217817228-ecdfe24d-1bd6-4007-8b9d-8a9acb5badca.png">
360 to Fisheye: The output is stretched, not centred and some pixels on the top are cut
<img width="668" alt="Bildschirm­foto 2023-02-08 um 20 03 15" src="https://user-images.githubusercontent.com/15050074/217819382-f3895689-f242-41b2-bb29-c1c344f8c29d.png">
I'm on Arena 7.13.1, M1 Max 64, macOS 13.0

**Comment by DanielArnett** [comment] 2023-02-09 22:06
The stretched output is by design, I wanted it to be the maximum resolution
it could possibly be, then folks could stretch it down to a 1:1 ratio if
needed.

Good bugs to find. I'm getting this built again. Visual Studio's being a
pain, apparently it uninstalled some of my dependencies so I'm having to
get the project set up again (even though I haven't touched VS since I last
worked on this project).

**Comment by xinaesthete** [comment] 2023-02-11 13:28
> <img alt="Bildschirm­foto 2023-02-08 um 19 50 53" width="664" src="https://user-images.githubusercontent.com/15050074/217624696-7ef5dc30-0bde-47b6-a3f1-98768028de7d.png">

I really don't know Resolume at all well, but in my experience pressing the 'maximise video' button a few times seems to cycle through a few different modes, and in my case I didn't encounter a situation where I couldn't get a seamless result.

![image](https://user-images.githubusercontent.com/674834/218260555-f705deb4-ff00-4b93-8060-af188e88c90c.png)

**Comment by DanielArnett** [comment] 2023-02-11 17:25
I'm trying to get to this tonight if I can wrap up some other projects
quick enough. But don't wait for me: what you can do now is this:

* Before the effect gets applied, try stretching the layer slightly
horizontally. See if that gets rid of the black line in the back.
* Try the same stretch vertically and see if it gets rid of the circle in
the top.

**Comment by xinaesthete** [comment] 2023-02-11 23:24
My double-negative probably obscured the clarity of my last message - I'd noticed this earlier and was going to mention it, but I found that the problem seems to go away after clicking that button a couple of times (such that it is stretching to the extents of the frame before being fed to the equi-rotation, I think).

**Comment by DanielArnett** [comment] 2023-02-13 13:58
Good to know. 

Update from me: I got the plugins building again. I'm just basing this as tightly off of the ffgl example as possible, because Resolume is just going to keep breaking my plugins like they have a few times in the last 5 years.

I added some dropdown boxes so I can change input/output projections. This new effect will be able to convert between any pair of projections in the list [ Equirectangular, fisheye, flat (rectilinear), cubemap ]. I can add others pretty easily if anyone can point me to the math. 

I'll keep chipping away at this and we should be able to get those other bugs fixed up as well. 
![image](https://user-images.githubusercontent.com/3029502/218476545-d5d8bd58-09f8-4634-ad25-897bcf8c414b.png)
![image](https://user-images.githubusercontent.com/3029502/218476619-8f8b0854-2710-41ec-9756-c5ff2ce439a7.png)

**Comment by DanielArnett** [comment] 2023-02-14 05:04
Okay everyone, this [new version](https://github.com/DanielArnett/360-VJ/releases/tag/8.0.0) is looking smooth and bug free. The math  is laid out much better and [the shader is packed into its own file](https://github.com/DanielArnett/360-VJ/blob/main/source/plugins/AddSubtract/Reprojection.hlsl). I have the updates on main if you want to check them out. To keep the diffs small everything is packed into the AddSubtract example project from Resolume, so next time they break my code the diff will be relatively small and easy to spot.

If someone can build this version for Mac we can close this ticket and enjoy a clean new effect. Thanks for your interest in this project.

**Comment by xinaesthete** [comment] 2023-02-15 11:39
New build here https://github.com/xinaesthete/360-VJ/releases/tag/0.2

**Comment by DanielArnett** [comment] 2023-02-15 12:57
@philipkrueger could you please try the new Reprojection shader and let us know how it works for you? 
[Reprojection.zip](https://github.com/DanielArnett/360-VJ/files/10743150/Reprojection.zip)

Thank you again for all your help @xinaesthete !

**Closed by DanielArnett** 2023-02-15 12:57 UTC

**Comment by xinaesthete** [comment] 2023-02-15 12:59
My pleasure @DanielArnett.

One last thing I might do before I forget is update the readme; it's still a bit non-obvious the steps currently needed to do the archive and get the bundle file out.

**Comment by philipkrueger** [comment] 2023-02-16 09:05
Great work! It's much better to have it all as one plugin. Reminds me to the Projection Top in Touchdesigner :)
I had to rename the file in Reprojection.bundle/MacOS from AddSubstract to Reprojection to get it listed in Arena and the seam on the backside still exists. The composition is in the same size as the test footage so it's not caused by wrong scaling.

**Comment by philipkrueger** [comment] 2023-02-16 09:07
Here is the renamed file:
[Reprojection.bundle.zip](https://github.com/DanielArnett/360-VJ/files/10754058/Reprojection.bundle.zip)
And the seam on the backside:
<img width="662" alt="Bildschirm­foto 2023-02-16 um 09 56 28" src="https://user-images.githubusercontent.com/15050074/219318946-f617e5b7-beed-4f7c-8267-f54e465b338d.png">

**Comment by philipkrueger** [comment] 2023-02-16 09:08
...and if I convert to Fisheye the tip is cut off:
<img width="665" alt="Bildschirm­foto 2023-02-16 um 09 58 44" src="https://user-images.githubusercontent.com/15050074/219319250-138c538e-906e-47e5-ae8d-242a7f010f8f.png">

**Comment by philipkrueger** [comment] 2023-02-16 09:12
...and if I convert to Flat the view is slightly rotated by default:
<img width="1094" alt="Bildschirm­foto 2023-02-16 um 10 11 37" src="https://user-images.githubusercontent.com/15050074/219320291-1d6d1c47-e903-4516-8575-6cae53cdf628.png">

**Comment by DanielArnett** [comment] 2023-02-16 14:45
Awesome, thanks. Separating this into it's own issue so folks don't get spammed.
https://github.com/DanielArnett/360-VJ/issues/10
